### ISSUE TITLE
CTC crashes when trying to dispatch a second time. Happens in DispatchPopUp.py

### ISSUE THREAD

**Issue by sush2023** [vism2889/ECE_1140_TRAINS#155]
File "C:\Users\achar\OneDrive\Desktop\fall_2022\trains\ECE_1140_TRAINS\Pittsburgh-Light-Rail-App\../CTC-Office/full-functionality\DispatchPopUp.py", line 121, in showTime
    self.scheduledMins = self.minuteSpinBox.value()
RuntimeError: wrapped C/C++ object of type QSpinBox has been deleted

The error is in DispatchPopUp.py

**Comment by beyonson** [comment]
i think the issue was that the hidden spinboxes go out of scope after a while, and they were referenced while hidden. i moved them inside a conditional that checks if they're shown
